using System.Collections.Generic;

/// <summary>
/// Yedek (varsayılan) çeviriler. JSON dosyasında anahtar yoksa LocalizationManager.Get buradan okur.
/// Böylece eksik JSON anahtarları ekranda ham anahtar adı olarak görünmez.
/// Sıra: [0]=Türkçe, [1]=İngilizce, [2]=Almanca. Diğer diller İngilizceye düşer.
/// </summary>
public static class LocalizationDefaults
{
    private static readonly Dictionary<string, string[]> Table = new Dictionary<string, string[]>
    {
        { "accept", new[] { "Kabul Et", "Accept", "Annehmen" } },
        { "ach_done", new[] { "KAZANILDI", "UNLOCKED", "FREIGESCHALTET" } },
        { "ach_locked", new[] { "KİLİTLİ", "LOCKED", "GESPERRT" } },
        { "ach_no_data", new[] { "Başarım verisi yok.", "No achievement data.", "Keine Erfolgsdaten." } },
        { "ach_title", new[] { "BAŞARIMLAR", "ACHIEVEMENTS", "ERFOLGE" } },
        { "ach_unlocked_fmt", new[] { "Kazanılan: {0} / {1} (global)", "Unlocked: {0} / {1} (global)", "Freigeschaltet: {0} / {1} (global)" } },
        { "cab_empty", new[] { "Kabinede kimse yok. Aktör verisi yüklenmemiş olabilir.", "The cabinet is empty. Actor data may not be loaded.", "Das Kabinett ist leer. Akteursdaten wurden evtl. nicht geladen." } },
        { "cab_opp_note1", new[] { "Muhalefettesiniz. İktidarın kabinesini göremezsiniz.", "You are in opposition. You cannot see the government's cabinet.", "Sie sind in der Opposition. Das Kabinett der Regierung ist nicht einsehbar." } },
        { "cab_opp_note2", new[] { "Gölge Kabine sekmesinden kendi ekibinizi kurabilirsiniz.", "You can build your own team in the Shadow Cabinet tab.", "Im Tab Schattenkabinett können Sie Ihr eigenes Team aufstellen." } },
        { "cabinet_dismiss", new[] { "Görevden Al (15 Sermaye)", "Dismiss (15 Capital)", "Entlassen (15 Kapital)" } },
        { "cabinet_members", new[] { "KABİNE ÜYELERİ", "CABINET MEMBERS", "KABINETTSMITGLIEDER" } },
        { "cabinet_open_ministries_fmt", new[] { "Açık Bakanlıklar: {0}/{1}", "Open Ministries: {0}/{1}", "Offene Ministerien: {0}/{1}" } },
        { "cabinet_portfolio_fmt", new[] { "Portföy: {0}", "Portfolio: {0}", "Ressort: {0}" } },
        { "cabinet_total", new[] { "Toplam: {0} kişi", "Total: {0} people", "Insgesamt: {0} Personen" } },
        { "cancel", new[] { "Vazgeç", "Cancel", "Abbrechen" } },
        { "candidate_campaign", new[] { "Adaylık Kampanyası", "Candidacy Campaign", "Kandidatenkampagne" } },
        { "candidate_crisis_warning", new[] { "ADAYLIK KRİZİ (UYARI)", "CANDIDACY CRISIS (WARNING)", "KANDIDATENKRISE (WARNUNG)" } },
        { "card_active_crises", new[] { "AKTİF KRİZLER", "ACTIVE CRISES", "AKTIVE KRISEN" } },
        { "card_budget", new[] { "BÜTÇE DENGESİ", "BUDGET BALANCE", "HAUSHALTSSALDO" } },
        { "card_coalition_partners", new[] { "KOALİSYON ORTAKLARI", "COALITION PARTNERS", "KOALITIONSPARTNER" } },
        { "card_coalition_status", new[] { "KOALİSYON DURUMU", "COALITION STATUS", "KOALITIONSSTATUS" } },
        { "card_demographics", new[] { "HALK GRUPLARI", "POPULATION GROUPS", "BEVÖLKERUNGSGRUPPEN" } },
        { "card_eco_stats", new[] { "EKONOMİK İSTATİSTİKLER", "ECONOMIC STATISTICS", "WIRTSCHAFTSSTATISTIKEN" } },
        { "card_heatmap", new[] { "MEMNUNİYET ISIL HARİTASI", "SATISFACTION HEATMAP", "ZUFRIEDENHEITS-HEATMAP" } },
        { "card_judiciary", new[] { "YARGI SİSTEMİ", "JUDICIAL SYSTEM", "JUSTIZSYSTEM" } },
        { "card_legislative_process", new[] { "YASAMA SÜRECİ", "LEGISLATIVE PROCESS", "GESETZGEBUNGSPROZESS" } },
        { "card_macro", new[] { "MAKRO GÖSTERGELER", "MACRO INDICATORS", "MAKROINDIKATOREN" } },
        { "card_migration", new[] { "GÖÇ VE DİASPORA", "MIGRATION AND DIASPORA", "MIGRATION UND DIASPORA" } },
        { "card_ministry_mgmt", new[] { "BAKANLIK YÖNETİMİ", "MINISTRY MANAGEMENT", "MINISTERIUMSVERWALTUNG" } },
        { "card_opposition_status", new[] { "MUHALEFET DURUMU", "OPPOSITION STATUS", "OPPOSITIONSSTATUS" } },
        { "card_party_fund", new[] { "PARTİ FONU (Muhalefet)", "PARTY FUNDS (Opposition)", "PARTEIKASSE (Opposition)" } },
        { "card_protest_status", new[] { "PROTESTO DURUMU", "PROTEST STATUS", "PROTESTSTATUS" } },
        { "card_radicalization", new[] { "RADİKALLEŞME DURUMU", "RADICALIZATION STATUS", "RADIKALISIERUNGSSTATUS" } },
        { "card_revenue_dist", new[] { "GELİR DAĞILIMI (Vergiler)", "REVENUE BREAKDOWN (Taxes)", "EINNAHMENVERTEILUNG (Steuern)" } },
        { "card_sectors", new[] { "EKONOMİK SEKTÖRLER", "ECONOMIC SECTORS", "WIRTSCHAFTSSEKTOREN" } },
        { "card_spending_dist", new[] { "GİDER DAĞILIMI", "SPENDING BREAKDOWN", "AUSGABENVERTEILUNG" } },
        { "card_state_status", new[] { "DEVLET DURUMU", "STATE OF THE NATION", "ZUSTAND DES STAATES" } },
        { "card_tech", new[] { "TEKNOLOJİ VE İNOVASYON", "TECHNOLOGY AND INNOVATION", "TECHNOLOGIE UND INNOVATION" } },
        { "card_your_shadow", new[] { "GÖLGE KABİNENİZ", "YOUR SHADOW CABINET", "IHR SCHATTENKABINETT" } },
        { "cd_pick", new[] { "Ülke seçin.", "Select a country.", "Land auswählen." } },
        { "cd_recent_actions", new[] { "SON EYLEMLER:", "RECENT ACTIONS:", "LETZTE AKTIONEN:" } },
        { "cd_selected_fmt", new[] { "Seçili ülke: {0}", "Selected country: {0}", "Ausgewähltes Land: {0}" } },
        { "cd_trust_fmt", new[] { "Bize Güven ({0})", "Trust in Us ({0})", "Vertrauen in uns ({0})" } },
        { "cd_trust_history", new[] { "GÜVEN GEÇMİŞİ:", "TRUST HISTORY:", "VERTRAUENSVERLAUF:" } },
        { "close", new[] { "Kapat", "Close", "Schließen" } },
        { "crisis_auto_resolve_fmt", new[] { "Otomatik çözülme: {0} tur", "Auto-resolves in: {0} turns", "Automatische Lösung: {0} Runden" } },
        { "crisis_stage_fmt", new[] { "Aşama {0}/{1}", "Stage {0}/{1}", "Stufe {0}/{1}" } },
        { "dec_desc", new[] { "Son 20 kararınız ve etkileri.", "Your last 20 decisions and their effects.", "Ihre letzten 20 Entscheidungen und ihre Auswirkungen." } },
        { "dec_impact_fmt", new[] { "Etki: {0}", "Impact: {0}", "Auswirkung: {0}" } },
        { "dec_none", new[] { "Henüz kayıtlı karar yok.", "No decisions recorded yet.", "Noch keine Entscheidungen aufgezeichnet." } },
        { "dec_title", new[] { "KARAR GÜNLÜĞÜ", "DECISION LOG", "ENTSCHEIDUNGSPROTOKOLL" } },
        { "default_player_name", new[] { "Başkan", "President", "Präsident" } },
        { "diff_easy", new[] { "Kolay", "Easy", "Leicht" } },
        { "diff_hard", new[] { "Zor", "Hard", "Schwer" } },
        { "diff_normal", new[] { "Normal", "Normal", "Normal" } },
        { "diff_very_hard", new[] { "Çok Zor", "Very Hard", "Sehr schwer" } },
        { "diplo_network_fmt", new[] { "Casus Ağı Gücü: %{0}", "Spy Network Strength: {0}%", "Spionagenetz-Stärke: {0}%" } },
        { "diplo_network_none", new[] { "Casus Ağı Gücü: -", "Spy Network Strength: -", "Spionagenetz-Stärke: -" } },
        { "diplo_relation_fmt", new[] { "İlişki: {0}", "Relations: {0}", "Beziehung: {0}" } },
        { "diplo_relation_none", new[] { "İlişki: -", "Relations: -", "Beziehung: -" } },
        { "eco_balance", new[] { "DENGE", "BALANCE", "SALDO" } },
        { "eco_brain_gain_fmt", new[] { "Beyin Kazanımı +{0}", "Brain Gain +{0}", "Brain-Gain +{0}" } },
        { "eco_brain_loss_fmt", new[] { "Beyin Kaybı {0}", "Brain Drain {0}", "Brain-Drain {0}" } },
        { "eco_comment_balanced", new[] { "Dengede - küçük fazla", "Balanced - small surplus", "Ausgeglichen - kleiner Überschuss" } },
        { "eco_comment_big_deficit", new[] { "Büyük açık - borç hızla artıyor!", "Large deficit - debt rising fast!", "Großes Defizit - Schulden steigen schnell!" } },
        { "eco_comment_critical", new[] { "KRİTİK: İflas riski! Vergileri artır!", "CRITICAL: Risk of bankruptcy! Raise taxes!", "KRITISCH: Insolvenzgefahr! Steuern erhöhen!" } },
        { "eco_comment_small_deficit", new[] { "Küçük açık - borç yavaş artıyor", "Small deficit - debt rising slowly", "Kleines Defizit - Schulden steigen langsam" } },
        { "eco_comment_surplus", new[] { "Bütçe fazlası - borç azalıyor", "Budget surplus - debt is shrinking", "Haushaltsüberschuss - Schulden sinken" } },
        { "eco_credit_rating", new[] { "Kredi Notu", "Credit Rating", "Kreditrating" } },
        { "eco_debt", new[] { "Ulusal Borç", "National Debt", "Staatsschulden" } },
        { "eco_gdp_share_fmt", new[] { "GSYİH %{0}", "GDP {0}%", "BIP {0}%" } },
        { "eco_inflation", new[] { "Enflasyon", "Inflation", "Inflation" } },
        { "eco_interest_burden", new[] { "Faiz Yükü (Borç)", "Interest Burden (Debt)", "Zinslast (Schulden)" } },
        { "eco_next_patent_fmt", new[] { "Sonraki patent: %{0}", "Next patent: {0}%", "Nächstes Patent: {0}%" } },
        { "eco_no_policies", new[] { "Aktif politika yok.", "No active policies.", "Keine aktiven Politiken." } },
        { "eco_no_stats", new[] { "İstatistik verisi yok.", "No statistics data.", "Keine Statistikdaten." } },
        { "eco_no_taxes", new[] { "Aktif vergi yok.", "No active taxes.", "Keine aktiven Steuern." } },
        { "eco_patents", new[] { "Patent Sayısı", "Patent Count", "Patentanzahl" } },
        { "eco_real_spending", new[] { "GERÇEK GİDER", "ACTUAL SPENDING", "TATSÄCHLICHE AUSGABEN" } },
        { "eco_rnd_budget", new[] { "Ar-Ge Bütçesi", "R&D Budget", "F&E-Budget" } },
        { "eco_sector_info_fmt", new[] { "İstihdam: %{0}  |  Verimlilik: %{1}", "Employment: {0}%  |  Productivity: {1}%", "Beschäftigung: {0}%  |  Produktivität: {1}%" } },
        { "eco_tech_bonus_fmt", new[] { "GSYİH Bonusu: +%{0}  |  Askeri Bonus: +%{1}  |  Yaptırım Direnci: +%{2}", "GDP Bonus: +{0}%  |  Military Bonus: +{1}%  |  Sanction Resistance: +{2}%", "BIP-Bonus: +{0}%  |  Militärbonus: +{1}%  |  Sanktionsresistenz: +{2}%" } },
        { "eco_tech_level", new[] { "Teknoloji Seviyesi", "Technology Level", "Technologieniveau" } },
        { "eco_total_revenue", new[] { "Toplam Gelir (Vergiler)", "Total Revenue (Taxes)", "Gesamteinnahmen (Steuern)" } },
        { "eco_total_spending", new[] { "Toplam Gider (Politikalar)", "Total Spending (Policies)", "Gesamtausgaben (Politik)" } },
        { "election_continue_gov", new[] { "Devleti Yönetmeye Devam Et", "Continue Governing", "Weiter regieren" } },
        { "election_defeat", new[] { "YENİLGİ", "DEFEAT", "NIEDERLAGE" } },
        { "election_results_title", new[] { "SEÇİM SONUÇLARI", "ELECTION RESULTS", "WAHLERGEBNISSE" } },
        { "election_start_opp", new[] { "Muhalefet Görevine Başla", "Begin Opposition Duty", "Oppositionsarbeit beginnen" } },
        { "election_victory", new[] { "ZAFER", "VICTORY", "SIEG" } },
        { "election_winner_fmt", new[] { "Kazanan: {0}", "Winner: {0}", "Gewinner: {0}" } },
        { "fac_appoint", new[] { "Bakan Ata (10 Sermaye)", "Appoint Minister (10 Capital)", "Minister ernennen (10 Kapital)" } },
        { "fac_challenge_fmt", new[] { "⚠️ MEYDAN OKUMA: {0} tur kaldı!", "⚠️ CHALLENGE: {0} turns left!", "⚠️ HERAUSFORDERUNG: noch {0} Runden!" } },
        { "fac_concede", new[] { "Taviz Ver (15 Sermaye)", "Concede (15 Capital)", "Zugeständnis (15 Kapital)" } },
        { "fac_demands", new[] { "AKTİF TALEPLER", "ACTIVE DEMANDS", "AKTIVE FORDERUNGEN" } },
        { "fac_desc", new[] { "Her fraksiyonun desteğini %20'nin üzerinde tut. Düşerse liderlik meydan okuması başlar.", "Keep every faction's support above 20%. If it drops, a leadership challenge begins.", "Halte die Unterstützung jeder Fraktion über 20 %. Fällt sie, beginnt eine Führungsherausforderung." } },
        { "fac_no_data", new[] { "Fraksiyon verisi yok.", "No faction data.", "Keine Fraktionsdaten." } },
        { "fac_title", new[] { "PARTİ İÇİ FRAKSİYONLAR", "INTRA-PARTY FACTIONS", "PARTEIINTERNE FRAKTIONEN" } },
        { "faction_ideologue", new[] { "İdeolog", "Ideologue", "Ideologe" } },
        { "faction_loyalist", new[] { "Sadık", "Loyalist", "Loyalist" } },
        { "faction_technocrat", new[] { "Teknokrat", "Technocrat", "Technokrat" } },
        { "frame_amount_fmt", new[] { "{0}:  {1} birim", "{0}:  {1} units", "{0}:  {1} Einheiten" } },
        { "frame_capital", new[] { "Sermaye İçin", "For Capital", "Für das Kapital" } },
        { "frame_people", new[] { "Halk İçin", "For the People", "Für das Volk" } },
        { "frame_pick_desc", new[] { "Söylem, yasanın ideolojik konumunu kaydırır ve meclis oylamasını etkiler.", "The framing shifts the law's ideological position and affects the parliamentary vote.", "Die Rahmung verschiebt die ideologische Position des Gesetzes und beeinflusst die Abstimmung im Parlament." } },
        { "frame_pick_title", new[] { "Söylem Seçin", "Choose a Framing", "Rahmung wählen" } },
        { "frame_state", new[] { "Devlet İçin", "For the State", "Für den Staat" } },
        { "hud_legit_title", new[] { "MEŞRUİYET", "LEGITIMACY", "LEGITIMITÄT" } },
        { "hud_public_support", new[] { "HALK DESTEĞİ", "PUBLIC SUPPORT", "VOLKSUNTERSTÜTZUNG" } },
        { "hud_turns_to_election", new[] { "SEÇİME KALAN", "TURNS TO ELECTION", "RUNDEN BIS ZUR WAHL" } },
        { "hud_turns_to_power", new[] { "İKTİDARA KALAN", "TURNS TO POWER", "RUNDEN BIS ZUR MACHT" } },
        { "ideology_center", new[] { "Merkez", "Center", "Mitte" } },
        { "ideology_center_left", new[] { "Merkez-Sol", "Center-Left", "Mitte-Links" } },
        { "ideology_center_right", new[] { "Merkez-Sağ", "Center-Right", "Mitte-Rechts" } },
        { "ideology_left", new[] { "Sol", "Left", "Links" } },
        { "ideology_right", new[] { "Sağ", "Right", "Rechts" } },
        { "ig_desc", new[] { "Bu gruplar doğrudan siyasi baskı uygular. Memnuniyetlerini yüksek tut.", "These groups apply direct political pressure. Keep their satisfaction high.", "Diese Gruppen üben direkten politischen Druck aus. Halte ihre Zufriedenheit hoch." } },
        { "ig_info_fmt", new[] { "Güç: %{0}   |   Lobi Bütçesi: {1}", "Power: {0}%   |   Lobby Budget: {1}", "Macht: {0}%   |   Lobbybudget: {1}" } },
        { "ig_lobby_btn", new[] { "Lobi Baskısı Uygula (20 Bütçe)", "Apply Lobby Pressure (20 Budget)", "Lobbydruck ausüben (20 Budget)" } },
        { "ig_no_data", new[] { "Çıkar grubu verisi yok.", "No interest group data.", "Keine Interessengruppen-Daten." } },
        { "ig_title", new[] { "ÇIKAR GRUPLARI", "INTEREST GROUPS", "INTERESSENGRUPPEN" } },
        { "judiciary_independence", new[] { "Yargı Bağımsızlığı", "Judicial Independence", "Unabhängigkeit der Justiz" } },
        { "legis_in_bureaucracy_fmt", new[] { "Bürokraside: {0}  ({1} tur kaldı)", "In bureaucracy: {0}  ({1} turns left)", "In der Bürokratie: {0}  (noch {1} Runden)" } },
        { "legis_none", new[] { "Bekleyen yasa yok.", "No pending laws.", "Keine ausstehenden Gesetze." } },
        { "legis_on_agenda_fmt", new[] { "Meclis gündeminde: {0}  (sonraki turda oylanacak)", "On parliament agenda: {0}  (will be voted next turn)", "Auf der Parlamentsagenda: {0}  (Abstimmung in der nächsten Runde)" } },
        { "migration_integration_fmt", new[] { "Entegrasyon ({0})", "Integration ({0})", "Integration ({0})" } },
        { "migration_low_integration", new[] { "⚠️ DÜŞÜK ENTEGRASYON: Sosyal gerginlik artıyor!", "⚠️ LOW INTEGRATION: Social tension is rising!", "⚠️ GERINGE INTEGRATION: Soziale Spannungen nehmen zu!" } },
        { "migration_net_in_fmt", new[] { "Net Göç Alan (+{0})", "Net Immigration (+{0})", "Netto-Einwanderung (+{0})" } },
        { "migration_net_out_fmt", new[] { "Net Göç Veren ({0})", "Net Emigration ({0})", "Netto-Auswanderung ({0})" } },
        { "migration_population", new[] { "Göçmen Nüfusu", "Immigrant Population", "Migrantenbevölkerung" } },
        { "migration_remittance_fmt", new[] { "Bekleyen Diaspora Havalesi: {0}", "Pending Diaspora Remittance: {0}", "Ausstehende Diaspora-Überweisung: {0}" } },
        { "news_none", new[] { "Henüz haber yok.", "No news yet.", "Noch keine Nachrichten." } },
        { "news_none_today", new[] { "Bugün önemli bir haber yok.", "No major news today.", "Heute keine wichtigen Nachrichten." } },
        { "obj_chain", new[] { "ETKİ ZİNCİRİ", "CHAIN OF EFFECTS", "WIRKUNGSKETTE" } },
        { "obj_equilibrium_fmt", new[] { "Denge noktası: %{0}  |  Atalet: %{1}", "Equilibrium: {0}%  |  Inertia: {1}%", "Gleichgewicht: {0}%  |  Trägheit: {1}%" } },
        { "obj_history_fmt", new[] { "Min: %{0}   |   Max: %{1}   |   Şimdi: %{2}", "Min: {0}%   |   Max: {1}%   |   Now: {2}%", "Min: {0}%   |   Max: {1}%   |   Jetzt: {2}%" } },
        { "obj_incoming", new[] { "◀ GELEN ETKİLER", "◀ INCOMING EFFECTS", "◀ EINGEHENDE EFFEKTE" } },
        { "obj_last20", new[] { "SON 20 TUR", "LAST 20 TURNS", "LETZTE 20 RUNDEN" } },
        { "obj_no_effect", new[] { "Şu an aktif bir etki yok.", "No active influence at the moment.", "Derzeit kein aktiver Einfluss." } },
        { "obj_outgoing", new[] { "▶ GİDEN ETKİLER", "▶ OUTGOING EFFECTS", "▶ AUSGEHENDE EFFEKTE" } },
        { "obj_sources", new[] { "ETKİ KAYNAKLARI", "SOURCES OF INFLUENCE", "EINFLUSSQUELLEN" } },
        { "ok", new[] { "Tamam", "OK", "OK" } },
        { "par_add_partner", new[] { "YENİ ORTAK EKLE", "ADD NEW PARTNER", "NEUEN PARTNER HINZUFÜGEN" } },
        { "par_candidate_fmt", new[] { "{0} ({1} sandalye, {2}, ideoloji {3})", "{0} ({1} seats, {2}, ideology {3})", "{0} ({1} Sitze, {2}, Ideologie {3})" } },
        { "par_coalition_majority_fmt", new[] { "Koalisyon çoğunluğu var: {0}/{1} sandalye.", "Coalition majority: {0}/{1} seats.", "Koalitionsmehrheit: {0}/{1} Sitze." } },
        { "par_composition", new[] { "MECLİS KOMPOZİSYONU", "PARLIAMENT COMPOSITION", "PARLAMENTSZUSAMMENSETZUNG" } },
        { "par_current_partners", new[] { "MEVCUT ORTAKLAR:", "CURRENT PARTNERS:", "AKTUELLE PARTNER:" } },
        { "par_gov_tag", new[] { " [HÜKÜMET]", " [GOVERNMENT]", " [REGIERUNG]" } },
        { "par_majority", new[] { "Çoğunluğunuz var — tek başına iktidardasınız. Koalisyona gerek yok.", "You have a majority — you govern alone. No coalition needed.", "Sie haben eine Mehrheit — Sie regieren allein. Keine Koalition nötig." } },
        { "par_ncb", new[] { "GÜVENSİZLİK ÖNERGESİ", "NO-CONFIDENCE MOTION", "MISSTRAUENSVOTUM" } },
        { "par_ncb_active", new[] { "⚠️ GÜVENSİZLİK ÖNERGESİ AKTİF", "⚠️ NO-CONFIDENCE MOTION ACTIVE", "⚠️ MISSTRAUENSVOTUM AKTIV" } },
        { "par_ncb_hint", new[] { "Devlet Menüsü'nden önerge verebilirsiniz.", "You can file a motion from the State Menu.", "Sie können im Staatsmenü einen Antrag stellen." } },
        { "par_ncb_turns_fmt", new[] { "Oylamaya {0} tur kaldı.", "{0} turns until the vote.", "Noch {0} Runden bis zur Abstimmung." } },
        { "par_need_election", new[] { "Koalisyon hükümeti kurmak için seçim kazanmalısınız.", "You must win an election to form a coalition government.", "Sie müssen eine Wahl gewinnen, um eine Koalitionsregierung zu bilden." } },
        { "par_no_data", new[] { "Meclis verisi yok.", "No parliament data.", "Keine Parlamentsdaten." } },
        { "par_no_majority_fmt", new[] { "Çoğunluk yok! {0} sandalye daha gerekli.", "No majority! {0} more seats needed.", "Keine Mehrheit! Es fehlen {0} Sitze." } },
        { "par_opp_support", new[] { "Muhalefet Desteği", "Opposition Support", "Oppositionsunterstützung" } },
        { "par_opp_support_fmt", new[] { "Muhalefet desteği: %{0}", "Opposition support: {0}%", "Oppositionsunterstützung: {0}%" } },
        { "par_partner_fmt", new[] { "{0} ({1} sandalye)", "{0} ({1} seats)", "{0} ({1} Sitze)" } },
        { "par_player_seats_fmt", new[] { "Partiniz {0} sandalyeye sahip. Muhalefettesiniz.", "Your party holds {0} seats. You are in opposition.", "Ihre Partei hat {0} Sitze. Sie sind in der Opposition." } },
        { "par_remove", new[] { "Çıkar", "Remove", "Entfernen" } },
        { "par_seats_fmt", new[] { "{0} sandalye{1}", "{0} seats{1}", "{0} Sitze{1}" } },
        { "par_title", new[] { "MECLİS", "PARLIAMENT", "PARLAMENT" } },
        { "par_total_fmt", new[] { "Toplam {0} sandalye   |   Baraj: %{1}", "Total {0} seats   |   Threshold: {1}%", "Insgesamt {0} Sitze   |   Hürde: {1}%" } },
        { "party_cost_fmt", new[] { "Maliyet: {0} sermaye + {1} fon", "Cost: {0} capital + {1} funds", "Kosten: {0} Kapital + {1} Mittel" } },
        { "party_default_name", new[] { "Yeni Parti", "New Party", "Neue Partei" } },
        { "party_found_btn", new[] { "Parti Kur", "Found Party", "Partei gründen" } },
        { "party_found_confirm", new[] { "PARTİYİ KUR", "FOUND THE PARTY", "PARTEI GRÜNDEN" } },
        { "party_found_title", new[] { "PARTİ KUR", "FOUND A PARTY", "PARTEI GRÜNDEN" } },
        { "party_fund_critical", new[] { "Fon kritik seviyede. Bağış kampanyası başlat!", "Funds are critical. Start a donation campaign!", "Mittel kritisch. Starte eine Spendenkampagne!" } },
        { "party_fund_label", new[] { "Fon", "Funds", "Mittel" } },
        { "party_fund_low", new[] { "Fon düşük. Devlet yardımı alabilirsin.", "Funds are low. You can receive state aid.", "Mittel niedrig. Du kannst Staatshilfe erhalten." } },
        { "party_fund_ok", new[] { "Fon sağlıklı.", "Funds are healthy.", "Mittel sind gesund." } },
        { "party_ideology_label", new[] { "İDEOLOJİ (Sol ←→ Sağ)", "IDEOLOGY (Left ←→ Right)", "IDEOLOGIE (Links ←→ Rechts)" } },
        { "party_name_label", new[] { "PARTİ ADI", "PARTY NAME", "PARTEINAME" } },
        { "party_name_placeholder", new[] { "Örn: Halkın Sesi Partisi", "e.g. Voice of the People Party", "z. B. Partei der Volksstimme" } },
        { "party_net_income", new[] { "Net Gelir", "Net Income", "Nettoeinkommen" } },
        { "party_reason_fmt", new[] { "Sebep:\n{0}", "Reason:\n{0}", "Grund:\n{0}" } },
        { "party_slogan_label", new[] { "SLOGAN", "SLOGAN", "SLOGAN" } },
        { "party_slogan_placeholder", new[] { "Örn: Değişim şimdi!", "e.g. Change now!", "z. B. Wandel jetzt!" } },
        { "people_in_gov", new[] { "hükümette", "in government", "in der Regierung" } },
        { "people_influence_fmt", new[] { "Siyasi ağırlık: %{0}", "Political weight: {0}%", "Politisches Gewicht: {0}%" } },
        { "people_low_sat_fmt", new[] { "düşük memnuniyet: {0} tur", "low satisfaction: {0} turns", "geringe Zufriedenheit: {0} Runden" } },
        { "people_out_coalition", new[] { "koalisyon dışı", "outside coalition", "außerhalb der Koalition" } },
        { "people_radicalized", new[] { "RADİKALLEŞTİ: her tur memnuniyet ve meşruiyet kaybettiriyor.", "RADICALIZED: costs satisfaction and legitimacy every turn.", "RADIKALISIERT: kostet jede Runde Zufriedenheit und Legitimität." } },
        { "per_turn_fmt", new[] { "{0}/tur", "{0}/turn", "{0}/Runde" } },
        { "pf_economy", new[] { "Ekonomi", "Economy", "Wirtschaft" } },
        { "pf_justice", new[] { "Adalet", "Justice", "Justiz" } },
        { "pf_social", new[] { "Sosyal", "Social", "Soziales" } },
        { "player_name_desc", new[] { "Ülkeyi yönetecek liderin adı ne olsun?", "What is the name of the leader who will rule the country?", "Wie heißt der Anführer, der das Land regieren wird?" } },
        { "player_name_placeholder", new[] { "Örn: Ahmet Yılmaz", "e.g. John Smith", "z. B. Max Mustermann" } },
        { "player_name_prompt", new[] { "ADINIZ", "YOUR NAME", "IHR NAME" } },
        { "pol_none", new[] { "Henüz yasa yok.", "No laws yet.", "Noch keine Gesetze." } },
        { "pol_opp_note", new[] { "Muhalefettesiniz: yasa öneremezsiniz. Miting, skandal ve kampanya ile iktidarı hedefleyin.", "You are in opposition: you cannot propose laws. Target the government with rallies, scandals and campaigns.", "Sie sind in der Opposition: Sie können keine Gesetze vorschlagen. Greifen Sie die Regierung mit Kundgebungen, Skandalen und Kampagnen an." } },
        { "policy_active", new[] { "AKTİF", "ACTIVE", "AKTIV" } },
        { "policy_in_bureaucracy_fmt", new[] { "BÜROKRASİDE ({0} tur)", "IN BUREAUCRACY ({0} turns)", "IN DER BÜROKRATIE ({0} Runden)" } },
        { "policy_inactive", new[] { "pasif", "inactive", "inaktiv" } },
        { "policy_on_agenda", new[] { "MECLİS GÜNDEMİNDE", "ON PARLIAMENT AGENDA", "AUF DER PARLAMENTSAGENDA" } },
        { "protest_cooldown_fmt", new[] { "Yeni protesto için {0} tur beklemelisin.", "You must wait {0} turns for a new protest.", "Du musst {0} Runden auf einen neuen Protest warten." } },
        { "protest_effect", new[] { "Her tur hükümet meşruiyeti düşüyor ve sokaklar hareketleniyor.", "Each turn the government loses legitimacy and the streets stir.", "Jede Runde sinkt die Legitimität der Regierung und die Straßen geraten in Bewegung." } },
        { "protest_info_fmt", new[] { "Tema: {0}   |   Yoğunluk: %{1}   |   Kalan: {2} tur", "Theme: {0}   |   Intensity: {1}%   |   Remaining: {2} turns", "Thema: {0}   |   Intensität: {1}%   |   Verbleibend: {2} Runden" } },
        { "protest_organize", new[] { "Protesto Düzenle", "Organize Protest", "Protest organisieren" } },
        { "protest_ready", new[] { "Protesto hazır. 'Protesto Düzenle' butonundan başlatabilirsin.", "Protest is ready. Start it with the 'Organize Protest' button.", "Der Protest ist bereit. Starte ihn mit der Schaltfläche 'Protest organisieren'." } },
        { "radical_tag", new[] { "RADİKAL", "RADICAL", "RADIKAL" } },
        { "rally_cost_fmt", new[] { "Maliyet: {0} siyasi sermaye. Her miting seçim kampanyasına da yatırım sayılır.", "Cost: {0} political capital. Every rally also counts as an investment in the election campaign.", "Kosten: {0} politisches Kapital. Jede Kundgebung zählt auch als Investition in den Wahlkampf." } },
        { "rally_start_btn", new[] { "MİTİNGİ BAŞLAT", "START RALLY", "KUNDGEBUNG STARTEN" } },
        { "rally_target_group", new[] { "HEDEF GRUP", "TARGET GROUP", "ZIELGRUPPE" } },
        { "rally_theme", new[] { "TEMA", "THEME", "THEMA" } },
        { "rally_theme_desc_anger", new[] { "Öfke: Etkisi büyüktür ama kutuplaştırır, huzursuzluğu artırır. Muhalefetteyken hükümete duyulan memnuniyeti düşürür.", "Anger: Powerful but polarizing; raises unrest. In opposition, it lowers satisfaction with the government.", "Wut: Starke Wirkung, aber polarisierend und steigert die Unruhe. In der Opposition senkt sie die Zufriedenheit mit der Regierung." } },
        { "rally_theme_desc_hope", new[] { "Umut: İktidardayken hedef grubun memnuniyetini artırır ve sokak huzursuzluğunu biraz düşürür.", "Hope: In government, raises the target group's satisfaction and slightly reduces street unrest.", "Hoffnung: In der Regierung steigert sie die Zufriedenheit der Zielgruppe und senkt die Unruhe auf der Straße leicht." } },
        { "rally_theme_desc_trust", new[] { "Güven: İktidardayken meşruiyeti yükseltir. Muhalefetteyken kampanya yatırımını güçlendirir.", "Trust: In government, raises legitimacy. In opposition, strengthens campaign investment.", "Vertrauen: In der Regierung steigert es die Legitimität. In der Opposition stärkt es die Kampagneninvestition." } },
        { "rally_title", new[] { "SİYASİ MİTİNG", "POLITICAL RALLY", "POLITISCHE KUNDGEBUNG" } },
        { "reject", new[] { "Reddet", "Reject", "Ablehnen" } },
        { "role_activist", new[] { "Aktivist", "Activist", "Aktivist" } },
        { "role_government", new[] { "HÜKÜMET", "GOVERNMENT", "REGIERUNG" } },
        { "role_minister", new[] { "Bakan", "Minister", "Minister" } },
        { "role_mp", new[] { "Milletvekili", "Member of Parliament", "Abgeordneter" } },
        { "role_oligarch", new[] { "Oligark", "Oligarch", "Oligarch" } },
        { "role_opposition", new[] { "MUHALEFET", "OPPOSITION", "OPPOSITION" } },
        { "role_opposition_leader", new[] { "Muhalefet lideri", "Opposition leader", "Oppositionsführer" } },
        { "scenario_desc", new[] { "Zorluk seviyesi ve başlangıç koşullarını belirle.", "Choose the difficulty level and starting conditions.", "Wähle Schwierigkeitsgrad und Startbedingungen." } },
        { "scenario_pick", new[] { "SENARYO SEÇ", "CHOOSE SCENARIO", "SZENARIO WÄHLEN" } },
        { "scenario_select_btn", new[] { "Bu Senaryoyu Seç", "Choose This Scenario", "Dieses Szenario wählen" } },
        { "shadow_appoint_btn_fmt", new[] { "{0} Portföyüne Ata", "Appoint to {0} Portfolio", "Für Ressort {0} ernennen" } },
        { "shadow_appoint_card", new[] { "YENİ GÖLGE BAKAN ATA", "APPOINT NEW SHADOW MINISTER", "NEUEN SCHATTENMINISTER ERNENNEN" } },
        { "shadow_bonus_fmt", new[] { "Tur başına bonus: +{0} siyasi sermaye", "Bonus per turn: +{0} political capital", "Bonus pro Runde: +{0} politisches Kapital" } },
        { "shadow_cost_fmt", new[] { "Maliyet: {0} siyasi sermaye (şu an: {1})", "Cost: {0} political capital (currently: {1})", "Kosten: {0} politisches Kapital (aktuell: {1})" } },
        { "shadow_current_fmt", new[] { "MEVCUT GÖLGE BAKANLAR ({0}/3)", "CURRENT SHADOW MINISTERS ({0}/3)", "AKTUELLE SCHATTENMINISTER ({0}/3)" } },
        { "shadow_desc_gov", new[] { "Şu an iktidardasın. Gölge kabine sadece muhalefetteyken kurulabilir. Seçimi kaybedersen önceki gölge bakanların devreye girer.", "You are in government. A shadow cabinet can only be formed in opposition. If you lose the election, your previous shadow ministers step in.", "Du bist an der Regierung. Ein Schattenkabinett kann nur in der Opposition gebildet werden. Verlierst du die Wahl, treten deine früheren Schattenminister ein." } },
        { "shadow_desc_opp", new[] { "Muhalefetteyken 3 gölge bakan atayabilirsin. Her biri +2 sermaye/tur üretir ve AI hükümetin yasalarını bloklar. İktidara gelince otomatik olarak gerçek bakan olurlar.", "In opposition you can appoint 3 shadow ministers. Each produces +2 capital/turn and blocks the AI government's laws. They automatically become real ministers when you take power.", "In der Opposition kannst du 3 Schattenminister ernennen. Jeder erzeugt +2 Kapital/Runde und blockiert Gesetze der KI-Regierung. An der Macht werden sie automatisch echte Minister." } },
        { "shadow_dismiss", new[] { "Görevden Al (-10)", "Dismiss (-10)", "Entlassen (-10)" } },
        { "shadow_stats_fmt", new[] { "Yetkinlik %{0}   |   Medya %{1}   |   Sadakat %{2}", "Competence {0}%   |   Media {1}%   |   Loyalty {2}%", "Kompetenz {0}%   |   Medien {1}%   |   Loyalität {2}%" } },
        { "shadow_title", new[] { "GÖLGE KABİNE", "SHADOW CABINET", "SCHATTENKABINETT" } },
        { "shadow_title_gov", new[] { "GÖLGE KABİNE (İKTİDAR)", "SHADOW CABINET (GOVERNMENT)", "SCHATTENKABINETT (REGIERUNG)" } },
        { "side_log", new[] { "OLAY GÜNLÜĞÜ", "EVENT LOG", "EREIGNISPROTOKOLL" } },
        { "side_news", new[] { "GÜNÜN HABERLERİ", "TODAY'S NEWS", "NACHRICHTEN DES TAGES" } },
        { "side_world_news", new[] { "DÜNYA HABERLERİ", "WORLD NEWS", "WELTNACHRICHTEN" } },
        { "since_last_turn", new[] { "son turdan", "since last turn", "seit der letzten Runde" } },
        { "sparkline_fmt", new[] { "min:{0} max:{1} ort:{2}", "min:{0} max:{1} avg:{2}", "min:{0} max:{1} Ø:{2}" } },
        { "start", new[] { "BAŞLA", "START", "START" } },
        { "stat_army_loyalty", new[] { "ORDU SADAKATİ", "ARMY LOYALTY", "ARMEELOYALITÄT" } },
        { "stat_army_satisfaction", new[] { "Ordu Memnuniyeti", "Army Satisfaction", "Armeezufriedenheit" } },
        { "stat_gdp", new[] { "GSYİH", "GDP", "BIP" } },
        { "stat_legitimacy", new[] { "Meşruiyet", "Legitimacy", "Legitimität" } },
        { "stat_loyalty", new[] { "Sadakat", "Loyalty", "Loyalität" } },
        { "stat_political_capital", new[] { "SİYASİ SERMAYE", "POLITICAL CAPITAL", "POLITISCHES KAPITAL" } },
        { "stat_satisfaction", new[] { "Memnuniyet", "Satisfaction", "Zufriedenheit" } },
        { "stat_street_unrest", new[] { "SOKAK HUZURSUZLUĞU", "STREET UNREST", "UNRUHE AUF DEN STRASSEN" } },
        { "stat_unrest", new[] { "Huzursuzluk", "Unrest", "Unruhe" } },
        { "tab_mods", new[] { "Modlar", "Mods", "Mods" } },
        { "mods_open_folder", new[] { "Klasörü Aç", "Open Folder", "Ordner öffnen" } },
        { "mods_refresh", new[] { "Yeniden Tara", "Rescan", "Neu scannen" } },
        { "mods_desc", new[] { "Topluluk ve oyuncu yapımı modlar burada listelenir. Değişikliklerin tam geçerli olması için yeni oyun açmanız veya oyunu yeniden başlatmanız önerilir.", "Community and player-created mods are listed here. Starting a new game or restarting is recommended after changes.", "Community- und Spielermods werden hier aufgelistet." } },
        { "mods_empty", new[] { "Kurulu mod bulunamadı. 'StreamingAssets/mods' klasörüne mod ekleyebilirsiniz.", "No mods found. You can add mods to 'StreamingAssets/mods'.", "Keine Mods gefunden." } },
        { "mod_active", new[] { "AKTİF", "ACTIVE", "AKTIV" } },
        { "mod_inactive", new[] { "KAPALI", "DISABLED", "DEAKTIVIERT" } },
        { "mods_refreshed", new[] { "Mod listesi güncellendi.", "Mod list updated.", "Mod-Liste aktualisiert." } },
        { "theme_anger", new[] { "Öfke", "Anger", "Wut" } },
        { "theme_hope", new[] { "Umut", "Hope", "Hoffnung" } },
        { "theme_trust", new[] { "Güven", "Trust", "Vertrauen" } },
        { "trait_ambitious", new[] { "hırslı", "ambitious", "ehrgeizig" } },
        { "trait_cautious", new[] { "temkinli", "cautious", "vorsichtig" } },
        { "trait_corrupt", new[] { "yolsuz", "corrupt", "korrupt" } },
        { "trait_loyal", new[] { "sadık", "loyal", "loyal" } },
        { "trait_populist", new[] { "popülist", "populist", "populistisch" } },
        { "trust_ally", new[] { "MÜTTEFİK", "ALLY", "VERBÜNDETER" } },
        { "trust_cold", new[] { "Soğuk", "Cold", "Kühl" } },
        { "trust_enemy", new[] { "DÜŞMAN", "ENEMY", "FEIND" } },
        { "trust_friendly", new[] { "Dostane", "Friendly", "Freundlich" } },
        { "trust_neutral", new[] { "Nötr", "Neutral", "Neutral" } },
        { "turn_label", new[] { "Tur {0}", "Turn {0}", "Runde {0}" } },
        { "turns_suffix_fmt", new[] { "{0} tur", "{0} turns", "{0} Runden" } },
        { "tut_capital", new[] { "Siyasi sermaye her eylemin bedelidir. Tükenmesine izin verme.", "Political capital is the price of every action. Don't let it run out.", "Politisches Kapital ist der Preis jeder Handlung. Lass es nicht ausgehen." } },
        { "tut_coalition", new[] { "Koalisyon ortakların memnun değilse hükümet düşebilir. Meclis sekmesini kontrol et.", "If your coalition partners are unhappy the government can fall. Check the Parliament tab.", "Sind deine Koalitionspartner unzufrieden, kann die Regierung fallen. Prüfe den Tab Parlament." } },
        { "tut_election", new[] { "Seçim yaklaşıyor! Miting yap, söz ver ve gruplarını memnun et.", "The election is approaching! Hold rallies, make promises and keep your groups happy.", "Die Wahl rückt näher! Halte Kundgebungen, mache Versprechen und halte deine Gruppen zufrieden." } },
        { "tut_groups", new[] { "Halk gruplarının memnuniyetini takip et. Düşük memnuniyet radikalleşmeye yol açar.", "Watch the satisfaction of population groups. Low satisfaction leads to radicalization.", "Beobachte die Zufriedenheit der Bevölkerungsgruppen. Geringe Zufriedenheit führt zu Radikalisierung." } },
        { "tut_opposition", new[] { "Muhalefetteydin: gölge kabine kur, miting ve protesto ile iktidara hazırlan.", "You are in opposition: build a shadow cabinet and prepare for power with rallies and protests.", "Du bist in der Opposition: Bilde ein Schattenkabinett und bereite dich mit Kundgebungen und Protesten auf die Macht vor." } },
        { "tut_policy", new[] { "Yasalar meclis oylamasına gider. Söylem seçimi oylamayı etkiler.", "Laws go to a parliamentary vote. Your framing choice affects the vote.", "Gesetze gehen zur Abstimmung ins Parlament. Deine Rahmung beeinflusst die Abstimmung." } },
        { "tut_unrest", new[] { "Sokak huzursuzluğu yükseliyor. Protestolar meşruiyetini aşındırabilir.", "Street unrest is rising. Protests can erode your legitimacy.", "Die Unruhe auf den Straßen wächst. Proteste können deine Legitimität untergraben." } },
        { "tut_vote", new[] { "Meclis oylaması sonuçlandı. Sonuç koalisyon ortaklarının memnuniyetine bağlıdır.", "The parliamentary vote has concluded. The result depends on your coalition partners' satisfaction.", "Die Parlamentsabstimmung ist abgeschlossen. Das Ergebnis hängt von der Zufriedenheit deiner Koalitionspartner ab." } },
        { "tut_welcome", new[] { "Hoş geldin! Önce \"Yeni Yasa Tasarla\" ile bir yasa öner, sonra \"Sonraki Tur\" ile ilerle.", "Welcome! First propose a law with \"Design New Policy\", then advance with \"Next Turn\".", "Willkommen! Schlage zuerst mit „Neues Gesetz entwerfen“ ein Gesetz vor und fahre dann mit „Nächste Runde“ fort." } },
        { "tut_world", new[] { "Dünya sekmesinden diplomasi yürüt, ticaret ve casusluk operasyonları başlat.", "Use the World tab for diplomacy, trade and espionage operations.", "Nutze den Tab Welt für Diplomatie, Handel und Spionageoperationen." } },
        { "ui_player_name_subtitle", new[] { "Ülkeyi yönetecek liderin adı ne olsun?", "What is the name of the leader who will rule the country?", "Wie heißt der Anführer, der das Land regieren wird?" } },
        { "ui_player_name_title", new[] { "ADINIZ", "YOUR NAME", "IHR NAME" } },
        { "unit_billion", new[] { " milyar", " billion", " Mrd." } },
        { "unit_points", new[] { " puan", " pts", " Pkt." } },
        { "unit_points_3turns", new[] { " puan (3 tur)", " pts (3 turns)", " Pkt. (3 Runden)" } },
        { "world_btn_back", new[] { "Genel ekrana dön", "Back to overview", "Zurück zur Übersicht" } },
        { "world_btn_intel", new[] { "Casusluk: gizli verileri ele geçir", "Espionage: steal secret data", "Spionage: Geheimdaten beschaffen" } },
        { "world_btn_manipulate", new[] { "Manipülasyon: halkı etkile", "Manipulation: influence the public", "Manipulation: Öffentlichkeit beeinflussen" } },
        { "world_btn_sabotage", new[] { "Sabotaj: altyapıya zarar ver", "Sabotage: damage infrastructure", "Sabotage: Infrastruktur beschädigen" } },
        { "world_covert", new[] { "GİZLİ OPERASYONLAR", "COVERT OPERATIONS", "GEHEIMOPERATIONEN" } },
        { "world_covert_warn", new[] { "Başarısız operasyon ilişkileri bozar ve meşruiyetinize zarar verir.", "A failed operation damages relations and hurts your legitimacy.", "Eine gescheiterte Operation schadet den Beziehungen und Ihrer Legitimität." } },
        { "world_internal", new[] { "ÜLKE İÇ DURUMU", "COUNTRY INTERNAL STATUS", "INNERER ZUSTAND DES LANDES" } },
        { "world_news_none", new[] { "Henüz dünya haberi yok.", "No world news yet.", "Noch keine Weltnachrichten." } },
        { "world_news_none_today", new[] { "Bugün dünya sahnesinde önemli bir gelişme yok.", "No major developments on the world stage today.", "Heute keine wichtigen Entwicklungen auf der Weltbühne." } },
        { "world_pick_above", new[] { "Yukarıdan bir ülke seçin.", "Select a country above.", "Wählen Sie oben ein Land aus." } },
        { "world_relations_card", new[] { "İLİŞKİ VE CASUS AĞI", "RELATIONS AND SPY NETWORK", "BEZIEHUNG UND SPIONAGENETZ" } },
        { "world_target", new[] { "HEDEF ÜLKE", "TARGET COUNTRY", "ZIELLAND" } },
    };

    public static bool Has(string key) => Table.ContainsKey(key);

    public static string Lookup(string key, Language lang)
    {
        if (!Table.TryGetValue(key, out var v)) return null;
        int i = lang == Language.Turkish ? 0 : (lang == Language.German ? 2 : 1);
        return v[i];
    }
}
